name: bench-django-blacksmith-cold
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install -e .
          python -m pip install -r tests/requirements/py3.txt
      - run: python tests/runtests.py
